version: '3.8'

services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"

  customer-assets-service:
    build: ./customer-assets-service
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://discovery-service:8761/eureka}
    depends_on:
      - discovery-service

  customer-branches-service:
    build: ./customer-branches-service
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://discovery-service:8761/eureka}
    depends_on:
      - discovery-service

  maintenance-reporting-service:
    build: ./maintenance-reporting-service
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://discovery-service:8761/eureka}
    depends_on:
      - discovery-service

  user-role-management-service:
    build: ./user-role-management-service
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://discovery-service:8761/eureka}
    depends_on:
      - discovery-service

  work-order-service:
    build:
      context: ./work-order-service
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://discovery-service:8761/eureka}
    depends_on:
      - discovery-service

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://discovery-service:8761/eureka}
      PATH_ALLOWED_ORIGIN: ${PATH_ALLOWED_ORIGIN}
    depends_on:
      - discovery-service
      - customer-assets-service
      - customer-branches-service
      - maintenance-reporting-service
      - user-role-management-service
      - work-order-service
