server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: user-role-management-service
          uri: lb://user-role-management-service
          predicates:
            - Path=/api/v1/users/**
        - id: customer-branches-service
          uri: lb://customer-branches-service
          predicates:
            - Path=/api/v1/customers/**
        - id: customer-assets-service
          uri: lb://customer-assets-service
          predicates:
            - Path=/api/v1/assets/**, /api-docs
        - id: maintenance-reporting-service
          uri: lb://maintenance-reporting-service
          predicates:
            - Path=/api/v1/maintenance/**
        - id: work-order-service
          uri: lb://work-order-service
          predicates:
            - Path=/api/v1/work-orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG