# Configuraci贸n del servidor
server:
  port: 0
  servlet:
    context-path: /api/v1/maintenance

# Nombre de la aplicaci贸n
spring:
  application:
    name: maintenance-reporting-service

  # Configuraci贸n de la base de datos (PostgreSQL)
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

# Cliente Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    preferIpAddress: true

# Configuraci贸n de Swagger OpenAPI (Springdoc)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
