spring.application.name=user-role-management-service

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

#server.servlet.context-path=/API/Examen/V1

server.port=8080

# Security Config
security.jwt.key.private=PrivateKey
security.jwt.user.generator=ASSET-TRACK-JWT